---
#
# Configuration for the Task runner
#
# See: https://taskfile.dev
#
# Required tools:
#
# - poetry: https://python-poetry.org/
# - pre-commit: https://pre-commit.com/
#
# yamllint disable rule:line-length

version: "3"

vars:
  PY_HOST_EXE: python3
  PY_VENV_EXE: .venv/bin/python3

tasks:
  default:
    cmds:
      - task: list

  build:
    desc: Generate artifacts
    cmds:
      - task: py:export

  clean:
    desc: Delete generated files for project
    cmds:
      - "{{.PY_VENV_EXE}} -m ruff clean -q"
      - for:
          [
            "__pycache__",
            ".coverage",
            ".mypy_cache",
            ".pytest_cache",
            "dist",
            "site",
            "tmp",
          ]
        cmd: rm -fr {{ .ITEM }}

  format:
    desc: Format code
    aliases: [fmt]
    cmds:
      - "{{.PY_VENV_EXE}} -m ruff check --select I --fix -q"
      - "{{.PY_VENV_EXE}} -m ruff format -q"

  lint:
    desc: Run all checks
    aliases: [check]
    cmds:
      - pre-commit run --all-files

  list:
    desc: List available tasks
    cmds:
      - task --list

  setup:
    desc: Set up environment for development
    aliases: [bootstrap]
    cmds:
      - poetry install
      - pre-commit install

  test:
    desc: Run all linting and tests
    cmds:
      - task: lint
      - task: py:unit

  upgrade:
    desc: Upgrade tools and dependencies
    cmds:
      - pre-commit autoupdate

  py:export:
    desc: Generate Python requirements files
    cmds:
      - poetry export -f requirements.txt --output requirements.txt
      - poetry export -f requirements.txt --with dev --output requirements-dev.txt

  py:lint:
    desc: Run Python checks
    cmds:
      - for: ["ruff-check", "ruff-format", "mypy"]
        cmd: pre-commit run {{.ITEM}} --all-files

  py:test:
    desc: Run all Python linting and tests
    cmds:
      - task: py:lint
      - task: py:unit

  py:unit:
    desc: Run Python unit tests
    cmds:
      - "{{.PY_VENV_EXE}} -m pytest"
